# Generated by Django 3.1.1 on 2020-09-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kinri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curve_name', models.CharField(max_length=200)),
                ('curve_currency', models.CharField(max_length=200)),
                ('interest_type', models.CharField(max_length=200)),
                ('curve_date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Ois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('bid', models.FloatField()),
                ('offer', models.FloatField()),
                ('kinri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpykinri.kinri')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('rate', models.FloatField()),
                ('kinri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpykinri.kinri')),
            ],
        ),
    ]
